SELECT
  age,
  dx_psa,
  pros_gleason,
--  bmi_curr,
  pros_exitage,
  weight_f,
  height_f,
#   rectal_history,
--  surg_age,
  pack_years,
  numbiopp,
  curative_hormp,
  curative_othp,
  curative_prostp,
  curative_radp,
  fh_cancer,
  pros_fh_cnt,
  brothers,
  sisters,
  diabetes_f,
  gallblad_f,
  hearta_f,
  hyperten_f,
  liver_comorbidity,
  osteopor_f,
  polyps_f,
  stroke_f,
  enlpros_f,
  infpros_f,
  prosprob_f,
  surg_biopsy,
  vasect_f,
  vasecta,
  dth_days
FROM
  prostate_screening.prostate_overall
WHERE dx_psa > 0.0 AND
      (pros_gleason NOT IN (0.0, 99.0))
--      AND dth_days!=''
